### ISSUE TITLE
Todo List about TAS tools

### ISSUE THREAD

**Issue by LozenChen** [LozenChen/TAS-Helper#4]
Here is what I plan to do

## GhostModForTas
- [ ] **☆ Output Improvement Log**
- [ ] GhostMod refactor: make it folder-based instead of UUID-based, and use metadata file to organize, so users can edit it manually.
- [ ] GhostMod support S&Q, and full game time compare
- [ ] GhostMod support comparing multiple tases more easily
- [ ] GhostMod repeated room numbering should be same as that of Studio

## TASHelper
- [ ] Refactor TAS Helper OoO Stepper (using CreateILCopy?)
- [ ] Enhance TAS Helper AutoWatch
- [ ] TAS Helper update to MonoMod v25 (see a recent update of Everest)
- [ ] Key cycle indicator (can be part of AutoWatch, or not)
- [ ] Refactor EntityActivator Watcher
- [ ] AutoWatch Trigger make GPU usage too low while CPU usage high

## SpeedrunTool
- [x] Multiple SaveSlots better UI
- [ ] Reduce Lag

## CelesteTAS
- [ ] CelesteTAS pull request 70: [Add RequireDependency Command](https://github.com/EverestAPI/CelesteTAS-EverestInterop/pull/70)
- [ ] CelesteTAS pull request (not created yet): config SimplifiedGraphics options in Studio, coz we can; and enhance it (e.g. handle GalleryCollab heartside blackscreen / vitmod RoomNameDisplay)

## Everest
- [ ] PR scrollable history log to Everest.
- [ ] Everest PR, Mod Loading Strategy, allow mod to choose [ load/unload itself, require/prevent other mod load ], when condition is satisfied, here condition can be like: version of some mod is >= A, <= B. The strategy can be provided by modders (using some metadata), and also by users [(see this)](https://github.com/EverestAPI/Everest/issues/745). This aims to prevent CelesteTAS-refactorization-related mod updating issues

## Other Projects
- [ ] HotkeyHelper https://github.com/LozenChen/HotkeyHelper
- [ ] CollabPartialLoader: when loading a single map of a collab, only need to load necessary dependencies instead of all dependencies of the collab.

## Done
- [x] ~~Anti VivHelper/HideRoomInMap (already done by CelesteTAS)~~
- [x] Spinner color changes after save load?
- [x] Refactor Add/RemoveImmediately
- [x] SRT pull request 35: [MoreSaveSlots](https://github.com/DemoJameson/Celeste.SpeedrunTool/pull/35), and thus refactor TAS Helper Predictor (also makes TAS Helper optionally depends on SRT)
- [x] (Jan 26th, 17:00 UTC+8) Upload latest version of TAS Helper, GhostModForTas, SpeedrunTool when CelesteTAS v3.42.0 release
- [x] Update SimplifiedChinese dialog of CelesteTAS before releasing v3.42.0
- [x] TAS Helper AutoWatch: Find a better way to use mouse actions, compatible with CelesteTAS mouse actions
- [x] ~~Remove TAS Helper hooks / publicizing on CelesteTAS, see [Fix compiler errors caused by CelesteTAS refactor](https://github.com/LozenChen/TAS-Helper/pull/3)~~ almost done, the rest involves some refactor of TAS Helper, see https://github.com/EverestAPI/CelesteTAS-EverestInterop/pull/91#issuecomment-2564735188
- [x] SRT support toggle grab mode, see [discord](https://discord.com/channels/403698615446536203/1316914508458885180/1316914508458885180)
- [x] SRT migrate to .NET Core
- [x] SRT export DeepClone() method
- [x] CelesteTAS issue 75: [LevelZoom by CenterCamera vs ExtendedVariantMode](https://github.com/EverestAPI/CelesteTAS-EverestInterop/issues/75)
- [x] CelesteTAS issue 78: [Feature Request: Support InfoHud in Overworld](https://github.com/EverestAPI/CelesteTAS-EverestInterop/issues/78)
- [x] CelesteTAS issue 79: [Bug: Stopping TAS when player is in StIntroWakeUp makes player stuck in StIntroWakeup](https://github.com/EverestAPI/CelesteTAS-EverestInterop/issues/79)
